apiVersion: v1
kind: Pod

metadata:
  name: xgboost1
  labels:
    team: platform

spec:
  containers:
  - name: xgboost
    image: rocketheat/ames-housing:v1
    volumeMounts:
    - mountPath: "/mnt/xgboost"
      name: datadir
    args:
      - --train-input
      - /mnt/xgboost/all/train.csv
      - --model-file
      - /mnt/xgboost/housing.dat
      - --learning-rate
      - "0.1"
      - --n-estimators
      - "30000"
      - --early-stopping-rounds
      - "50"
  volumes:
  - name: datadir
    persistentVolumeClaim:
      claimName: claim
